# 'int' object is not callable
~~~python
01 res = [] # 결과값
02 for i in range(len(data)): # 3 3 6 / 2 2 2 / 6 2 5 
03     max = 0 # 최대 중복 횟수
04     num = 0 # 중복되는 수    
05     for j in range(len(data[i])): # 6 / 2 / 5
06         a = data[i].count(data[i][j])
07         if max < a:
08             max = a
09             num = data[i][j]
~~~
> - Line 03에서 max를 변수명으로 지정하면서 발생한 오류  
> - 변수명 변경 후 해결  
