# ImportError: cannot import name 'six' from 'django.utils'
> - Django의 현재 버전과 API의 호환 문제로 인해 발생하는 오류  
> - Django의 버전을 다운그레이드하여 해결  
